server:
  port: ${SERVER_PORT:8282}

spring:
  application:
    name: ms-gateway
  cloud:
    gateway:
      routes:
        - id: ms-product
          uri: lb://MS-PRODUCT
          predicates:
            - Path=/ms-product/**
          filters:
            - RewritePath=/ms-product/(?<remaining>.*), /$\{remaining}

eureka:
  instance:
    preferIpAddress: false
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
